CREATE TABLE test_table (
    id SERIAL PRIMARY KEY,  
    column_name VARCHAR(255) NOT NULL,  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);

CREATE TABLE test_complex_table (
    id SERIAL PRIMARY KEY,  
    param1_1 VARCHAR(255) NOT NULL,
    param1_2 VARCHAR(255) NOT NULL,
    param1_3 VARCHAR(255) NOT NULL,
    param1_4 VARCHAR(255) NOT NULL,
    param_unused_1 VARCHAR(255) NOT NULL,
    param_unused_2 VARCHAR(255) NOT NULL,
    param2_1 VARCHAR(255) NOT NULL,
    param2_2 VARCHAR(255) NOT NULL,
    param2_3 VARCHAR(255) NOT NULL,
    param3_1 VARCHAR(255) NOT NULL,
    param3_2 VARCHAR(255) NOT NULL,
    param3_3 VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);

CREATE TABLE test_complex_table2 (
    id SERIAL PRIMARY KEY,  
    column_name VARCHAR(255) NOT NULL,  
    param1 INT NOT NULL,
    param2 INT NOT NULL,
    param3 INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);